###
@api_v2_1 = http://new.loc/v2
#@api_v2_1 = http://new.loc/app/v2

###

POST {{api_v2_1}}/login HTTP/1.1
Content-Type: application/json

{
    "phone": "777123123123",
    "password": "123456"
}
###

POST {{api_v2_1}}/signup HTTP/1.1
Content-Type: application/json

{
    "phone": "777123123123"
}
###

POST {{api_v2_1}}/signup/verify-phone HTTP/1.1
Content-Type: application/json

{
    "phone": "71053697123",
    "code": 72510
}

###

POST {{api_v2_1}}/signup/data/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzczNzg5ODAsImlzcyI6InRva2VuLmFjY291bnQudG1wIiwiZXhwIjoxNTM3MzgyNTgwLCJ1c2VyX2lkIjoiNDgiLCJwaG9uZSI6IjcxMDUzNjk3MTIzIn0.I_Ruztm_-bkRpL0Gqwa-0r8Xb5RT9aHjNkqa6UGVXs0

{
    "password": "dw31231",
    "name": "sdq",
    "lastname": "dq",
    "birthday": "1999-03-12",
    "gender": "male",
    "inviter_id": 1234
}
###

GET {{api_v2_1}}/user/data/ HTTP/1.1
Content-Type: application/json

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MzA2NTksImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAxMjI2NTksInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJEJyQTVKYkFoaGFTN09icXZidlFVVi45dEFWdVN0WFJSQmk4bHJDcUh2NmNyVUVabkRFUmxLIn0.uk6YLIs9HfojRKlNer070--OeB3CGfh3jfgsMwyHPsU"
}
###

PUT {{api_v2_1}}/user/data/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MTYxNjgsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAxMDgxNjgsInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJGwyTnE4Yk1iTlJiVU01Qndad3lMaGViOTg2blVVQ1wvenJjM0cydGdReDd3ek5tR0NjWjhkaSJ9.EoN4_mLrgRikG316OSOw6FHOjF4SHXT7lN31ubzxu20

{
    "gender": "male",
    "name": "Ismail",
    "region": "Актобе",
    "city": "Юнис Сити"
}
###

POST {{api_v2_1}}/password/forgot HTTP/1.1
Content-Type: application/json

{
    "phone": "77472995982"
}
###

POST {{api_v2_1}}/user/data/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MDcyMzgsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAwOTkyMzgsInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJGwyTnE4Yk1iTlJiVU01Qndad3lMaGViOTg2blVVQ1wvenJjM0cydGdReDd3ek5tR0NjWjhkaSJ9.8jkiUYvUw-qLEY2C1kzjvxsCaT76D9LlTo495rzXW8k

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="ava.jpeg"
Content-Type: image/jpeg

< ./test.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

GET {{api_v2_1}}/user/data/avatar/ HTTP/1.1
Content-Type: application/json

{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MTYxNjgsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAxMDgxNjgsInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJGwyTnE4Yk1iTlJiVU01Qndad3lMaGViOTg2blVVQ1wvenJjM0cydGdReDd3ek5tR0NjWjhkaSJ9.EoN4_mLrgRikG316OSOw6FHOjF4SHXT7lN31ubzxu20"
} 
### one month

DELETE {{api_v2_1}}/user/data/avatar/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MTYxNjgsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAxMDgxNjgsInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJGwyTnE4Yk1iTlJiVU01Qndad3lMaGViOTg2blVVQ1wvenJjM0cydGdReDd3ek5tR0NjWjhkaSJ9.EoN4_mLrgRikG316OSOw6FHOjF4SHXT7lN31ubzxu20

{
    "photo_id": 211
} 
###

###

POST {{api_v2_1}}/password/forgot/verify-phone/ HTTP/1.1
Content-Type: application/json

{
    "phone": "77472995982",
    "code": 44508
}
###

POST {{api_v2_1}}/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc0NDM5ODgsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAwMzU5ODgsInVzZXJfaWQiOiIyNSIsInBob25lIjoiNzc0NzI5OTU5ODIiLCJwYXNzd29yZCI6IiQyeSQxMCRSTmMzQzBVOW9SUUZiUENIa2lzQzJlWTJwVDFWd29WbmtyeC4yTnptSzdFOFlzS1NxeG4weSJ9.3q12MYQS5HuMjeLir73IeGOXR3Q2meSSXDN-OF_ATqw

{
    "type": "forgot",
    "new_password": "12122121"
}
###

POST {{api_v2_1}}/link/network/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mzc1MzA2NTksImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1NDAxMjI2NTksInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJEJyQTVKYkFoaGFTN09icXZidlFVVi45dEFWdVN0WFJSQmk4bHJDcUh2NmNyVUVabkRFUmxLIn0.uk6YLIs9HfojRKlNer070--OeB3CGfh3jfgsMwyHPsU

###

POST {{api_v2_1}}/encode/sayrus HTTP/1.1
Content-Type: application/json

{
    "jwt_secret": "asdasdasd",
    "payload": {
        "user_id": 2,
        "phone": "77773697417"
    }
}