###
@api_v2_1 = http://new.loc/v2

###

POST {{api_v2_1}}/login/ HTTP/1.1
Content-Type: application/json

{
    "phone": "+7 (777) 369-7417",
    "password": "12122121Isa"
}
###

POST {{api_v2_1}}/signup/ HTTP/1.1
Content-Type: application/json

{
    "phone": "+7 (105) 369-7415"
}
###

POST {{api_v2_1}}/signup/verify-phone HTTP/1.1
Content-Type: application/json

{
    "phone": "71053697415",
    "code": 31185
}

###

POST {{api_v2_1}}/signup/data HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzczNjIzNTYsImlzcyI6ImFjY291bnQub3RhdS5vcmciLCJleHAiOjE1Mzk5NTQzNTYsInVzZXJfaWQiOiIyIiwicGhvbmUiOiI3Nzc3MzY5NzQxNyIsInBhc3N3b3JkIjoiJDJ5JDEwJGwyTnE4Yk1iTlJiVU01Qndad3lMaGViOTg2blVVQ1wvenJjM0cydGdReDd3ek5tR0NjWjhkaSJ9.q-FKgjMYHdKiKhUfydT2tJ_F4ohrJ1ba_ppbyXT2NvU

{

}